# Generated by Django 3.1.2 on 2021-02-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210223_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
