# Generated by Django 3.1.2 on 2021-03-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210309_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='pic_url',
            new_name='pic',
        ),
    ]
