# Generated by Django 3.1.2 on 2021-03-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210325_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pic_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
