# Generated by Django 3.1.2 on 2021-03-25 11:59

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Listing = apps.get_model('auctions', 'Listing')
    for row in Listing.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210325_1159'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]