# Generated by Django 3.1.2 on 2021-06-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210528_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='won_at',
            new_name='closed_at',
        ),
    ]
