# Generated by Django 3.1.2 on 2021-06-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210614_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcomment',
            name='comment',
            field=models.CharField(default='placeholder', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingcomment',
            name='title',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
