# Generated by Django 3.1.2 on 2021-06-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210622_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingComment',
        ),
    ]
